sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t kim2108pw/docker-react-app -f Dockerfile.dev ./

script:
 - docker run -e CI=true kim2108pw/docker-react-app npm run start -- --coverage

after_success:
 - echo "Test Success"